links:
  rails_tutorial:
    home_page: https://www.railstutorial.org/
    help_page: https://www.railstutorial.org/help
    rails_tutorials: https://www.railstutorial.org/book
    learn_enough: https://www.learnenough.com/
    screencast_series: https://screencasts.railstutorial.org/
    ruby_onrails: https://rubyonrails.org/
